name: CI Action
on: 
  pull_request:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Get commit message
        run: echo "Commit message: $(git log --format=%B -n 1 ${{ github.event.after }})"
        shell: bash

      - name: Get changed files
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }}
        shell: bash